CC=clang
CXX=clang++
CFLAGS = -Wall -Wextra -O2
CXXFLAGS= $(CFLAGS) -std=c++0x -stdlib=libc++

CPP_COMMON= ./OpenCL/CppCommon/
CXXFLAGS += -I $(CPP_COMMON)

SRCS=$(wildcard ./host/*.cpp)
OBJS=$(subst .cpp,.o,$(SRCS))

# Runner: ./host/Runner.cpp
# 	$(CPPC) $^ $(INC) $(CCFLAGS) $(LIBS) -o $@

all: $(OBJS)
	@echo Compiling...;

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
	rm -f ./host/*.o
